[[redirects]]
  from = "/anomaly/*"
  to = "https://cmu-anomaly.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/archive/datathon-2024/*"
  to = "https://datathon-splash-2024.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/archive/pokerai-2024/*"
  to = "https://poker-splash-2024.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/archive/pokerai-2025/*"
  to = "https://poker-splash-2025.netlify.app/:splat"
  status = 200
  force = true

[build]
  command = "bun run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "bun run dev"
  targetPort = 4321
  port = 8888
  publish = "dist"
  framework = "astro"

[functions."github-contributions-scheduled"]
  schedule = "0 */3 * * *"